services:
  mongodb:
    restart: always
    image: mongo:latest
    # container_name: mongodb
    ports:
      - ${MONGODB_PORT}:27017
    command:
      - --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - ../data/mongo/db:/data/db
      - ../data/mongo/backup:/data/backup
    networks:
      - db-network

  # ngrok:
  #   restart: always
  #   image: ngrok/ngrok
  #   # container_name: ngrok
  #   ports:
  #     - 4040:4040
  #   command:
  #     - "start"
  #     - "mongodb"
  #     - "--config"
  #     - "/etc/ngrok.yml"
  #   volumes:
  #     - ../ngrok/ngrok.yaml:/etc/ngrok.yml
  #   environment:
  #     - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
  #   networks:
  #     - db-network

networks:
  db-network:
    driver: bridge
