name: "Setup SSH Keys"

description: "Setup SSH configuration on runners"

runs:
  using: "composite"
  steps:
    - name: Add IP to ~/.ssh/known_hosts
      shell: bash
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan $SSH_IP >> ~/.ssh/known_hosts
    - name: Add ssh private key
      shell: bash
      run: |
        eval $(ssh-agent)
        ssh-add - <<< "$SSH_KEY"
        echo "$SSH_KEY" > ~/.ssh/id_cloud
        chmod 0600 ~/.ssh/id_cloud
    - name: Create ssh config file
      shell: bash
      run: |
        echo "
        Host remote
          HostName $SSH_IP
          User $SSH_USER
          IdentityFile ~/.ssh/id_cloud
        " > ~/.ssh/config
