name: "Setup Cloud Credentials"

description: "Setup AWS and GCP credentials"

inputs:
  ssh_host:
    description: "SSH Host"
    required: true
  add_firebase_credentials:
    description: "Optionally add Firebase credentials"
    required: false

runs:
  using: "composite"
  steps:
    - name: Create aws credentials file
      shell: bash
      run: |
        ssh ${{ inputs.ssh_host }} "
          mkdir -p ~/.aws
          echo $AWS_CREDENTIALS | base64 --decode > ~/.aws/credentials
          chmod 644 ~/.aws/credentials
        "
    - name: Create gcs credentials file
      shell: bash
      run: |
        ssh ${{ inputs.ssh_host }} "
          mkdir -p ~/.gcp
          echo $GCS_CREDENTIALS | base64 --decode > ~/.gcp/gcs-credentials.json
          chmod 644 ~/.gcp/gcs-credentials.json
        "
    - name: Create firebase credentials file
      if: ${{ inputs.add_firebase_credentials }}
      shell: bash
      run: |
        ssh ${{ inputs.ssh_host }} "
          mkdir -p ~/.gcp
          echo $FIREBASE_CREDENTIALS | base64 --decode > ~/.gcp/firebase-credentials.json
          chmod 644 ~/.gcp/firebase-credentials.json
        "
