name: "Setup Cloud Credentials"

description: "Setup AWS and GCP credentials"

inputs:
  ssh_ip:
    description: "The IP address of the SSH server"
    required: true
  aws_credentials:
    description: "AWS credentials"
    required: true
  gcs_credentials:
    description: "GCS credentials"
    required: true
  firebase_credentials:
    description: "Firebase credentials"
    required: false

runs:
  using: "composite"
  steps:
    - name: Create aws credentials file
      shell: bash
      run: |
        ssh -i ~/.ssh/id_cloud ${{ inputs.ssh_ip }} "
          mkdir -p ~/.aws
          echo ${{ inputs.aws_credentials }} | base64 --decode > ~/.aws/credentials
          chmod 644 ~/.aws/credentials
        "
    - name: Create gcs credentials file
      shell: bash
      run: |
        ssh -i ~/.ssh/id_cloud ${{ inputs.ssh_ip }} "
          mkdir -p ~/.gcp
          echo ${{ inputs.gcs_credentials }} | base64 --decode > ~/.gcp/gcs-credentials.json
          chmod 644 ~/.gcp/gcs-credentials.json
        "
    - name: Create firebase credentials file
      if: ${{ inputs.firebase_credentials }}
      shell: bash
      run: |
        ssh -i ~/.ssh/id_cloud ${{ inputs.ssh_ip }} "
          mkdir -p ~/.gcp
          echo ${{ inputs.firebase_credentials }} | base64 --decode > ~/.gcp/firebase-credentials.json
          chmod 644 ~/.gcp/firebase-credentials.json
        "
