name: "Setup Certificates"

description: "Setup Certificates on remote VMs"

inputs:
  ssh_host:
    description: "SSH Host"
    default: "remote"
    required: false
  add_client_certificate:
    description: "Optionally add client certificate"
    required: false

runs:
  using: "composite"
  steps:
    - name: Create mongodb CA certificate
      shell: bash
      run: |
        ssh ${{ inputs.ssh_host }} "
          cd $REPO_NAME
          mkdir -p certs/mongodb
          echo $MONGO_CERT_CA_PEM | base64 --decode > certs/mongodb/ca.pem
        "
    - name: Create mongodb server certificate
      shell: bash
      run: |
        ssh ${{ inputs.ssh_host }} "
          cd $REPO_NAME
          mkdir -p certs/mongodb
          echo $MONGO_CERT_SERVER_PEM | base64 --decode > certs/mongodb/mongodb.pem
        "
    - name: Create mongodb client certificate
      if: ${{ inputs.add_client_certificate }}
      shell: bash
      run: |
        ssh ${{ inputs.ssh_host }} "
          cd $REPO_NAME
          mkdir -p certs/mongodb
          echo $MONGO_CERT_CLIENT_PEM | base64 --decode > certs/mongodb/client.pem
        "
