name: Deploy Application to Cloud

on:
  workflow_run:
    workflows: [Docker Image CI]
    types: [completed]
    branches: [main]

  workflow_dispatch:

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  SSH_USER: ${{secrets.SSH_USER}}
  SSH_KEY: ${{secrets.SSH_KEY}}
  SSH_IP: ${{secrets.SSH_IP}}
  NGROK_AUTHTOKEN: ${{secrets.NGROK_AUTHTOKEN}}
  LOCALTONET_AUTHTOKEN: ${{secrets.LOCALTONET_AUTHTOKEN}}
  AWS_CREDENTIALS: ${{secrets.AWS_CREDENTIALS}}
  GCS_CREDENTIALS: ${{secrets.GCS_CREDENTIALS}}
  FIREBASE_CREDENTIALS: ${{secrets.FIREBASE_CREDENTIALS}}
  MONGODB_STRING : ${{secrets.MONGODB_STRING}}
  ENVIRONMENT: ${{secrets.ENVIRONMENT}}
  BUCKET_NAME: ${{secrets.BUCKET_NAME}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Get current repo name
        run: echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
      - name: Add IP to known_host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan $SSH_IP >> ~/.ssh/known_hosts
      - name: Add ssh private key
        run: |
          eval $(ssh-agent)
          ssh-add - <<< "$SSH_KEY"
          echo "$SSH_KEY" > ~/.ssh/id_cloud
          chmod 0600 ~/.ssh/id_cloud
      - name: Get the docker-compose file
        run: |
            ssh -i ~/.ssh/id_cloud $SSH_USER@$SSH_IP "
                if [ ! -d $REPO_NAME ]; then git clone https://github.com/blurrycontour/remember.git; fi
                cd remember
                git fetch
                git reset --hard $GITHUB_SHA
            "
      - name: Create aws credentials file
        run: |
          ssh -i ~/.ssh/id_cloud $SSH_USER@$SSH_IP "
            mkdir -p ~/.aws
            echo $AWS_CREDENTIALS | base64 --decode > ~/.aws/credentials
            chmod 644 ~/.aws/credentials
          "
      - name: Create gcp credentials file
        run: |
          ssh -i ~/.ssh/id_cloud $SSH_USER@$SSH_IP "
            mkdir -p ~/.gcp
            echo $GCS_CREDENTIALS | base64 --decode > ~/.gcp/gcs-credentials.json
            chmod 644 ~/.gcp/gcs-credentials.json
            echo $FIREBASE_CREDENTIALS | base64 --decode > ~/.gcp/firebase-credentials.json
            chmod 644 ~/.gcp/firebase-credentials.json
          "
      - name: Get the short commit sha
        run: |
          short_sha=$(git rev-parse --short $GITHUB_SHA)
          echo "COMMIT_SHORT_SHA=$short_sha" >> $GITHUB_ENV
          echo "COMMIT_SHORT_SHA=$short_sha"
      - name: Create .env from .env.template file
        run: ssh -i ~/.ssh/id_cloud $SSH_USER@$SSH_IP "cd $REPO_NAME; cp .env.template .env"
      - name: Add ngrok authtoken to .env
        run: ssh -i ~/.ssh/id_cloud $SSH_USER@$SSH_IP "cd $REPO_NAME; echo 'NGROK_AUTHTOKEN=$NGROK_AUTHTOKEN' >> .env"
      - name: Add localtonet authtoken to .env
        run: ssh -i ~/.ssh/id_cloud $SSH_USER@$SSH_IP "cd $REPO_NAME; echo 'LOCALTONET_AUTHTOKEN=$LOCALTONET_AUTHTOKEN' >> .env"
      - name: Add mongodb credentials to .env
        run: |
          ssh -i ~/.ssh/id_cloud $SSH_USER@$SSH_IP "
            cd $REPO_NAME
            echo 'MONGODB_STRING=$MONGODB_STRING' >> .env
            echo 'ENVIRONMENT=$ENVIRONMENT' >> .env
            echo 'BUILD_VERSION=${{ env.COMMIT_SHORT_SHA }}' >> .env
          "
      - name: Add bucket name to .env
        run: ssh -i ~/.ssh/id_cloud $SSH_USER@$SSH_IP "cd $REPO_NAME; echo 'BUCKET_NAME=$BUCKET_NAME' >> .env"
      - name: Pull latest images
        run: ssh -i ~/.ssh/id_cloud $SSH_USER@$SSH_IP "cd $REPO_NAME; docker compose --profile deploy pull"
      - name: Stop existing containers
        run: ssh -i ~/.ssh/id_cloud $SSH_USER@$SSH_IP "cd $REPO_NAME; docker compose --profile '*' down"
      - name: Prune dangling images
        run: ssh -i ~/.ssh/id_cloud $SSH_USER@$SSH_IP "docker image prune -f"
      - name: Start containers again
        run: ssh -i ~/.ssh/id_cloud $SSH_USER@$SSH_IP "cd $REPO_NAME; docker compose --profile deploy up -d"
