name: Deploy Database to Cloud

on:
  workflow_dispatch:
    inputs:
      external_ip:
        description: "Server IP Address"
        default: ""

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  SSH_USER: ${{secrets.SSH_USER}}
  SSH_KEY: ${{secrets.SSH_KEY}}
  SSH_IP: ${{ github.event.inputs.external_ip }}
  NGROK_AUTHTOKEN: ${{secrets.NGROK_AUTHTOKEN}}
  AWS_CREDENTIALS: ${{secrets.AWS_CREDENTIALS}}
  GCS_CREDENTIALS: ${{secrets.GCS_CREDENTIALS}}
  MONGO_ROOT_USERNAME: ${{secrets.MONGO_ROOT_USERNAME}}
  MONGO_ROOT_PASSWORD: ${{secrets.MONGO_ROOT_PASSWORD}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get current repo name
        run: echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
      - uses: ./.github/actions/setup-ssh-keys
        with:
          ssh_ip: $SSH_IP
          ssh_key: $SSH_KEY
      - uses: ./.github/actions/setup-cloud-credentials
        with:
          ssh_host: "remote"
      - name: Get the docker-compose file
        run: |
            ssh remote "
                if [ ! -d $REPO_NAME ]; then git clone https://github.com/blurrycontour/remember.git; fi
                cd remember
                git fetch
                git reset --hard $GITHUB_SHA
            "
      - name: Create .env from .env.template file
        run: ssh remote "cd $REPO_NAME; cp .env.template .env"
      - name: Add ngrok authtoken to .env
        run: ssh remote "cd $REPO_NAME; echo 'NGROK_AUTHTOKEN=$NGROK_AUTHTOKEN' >> .env"
      - name: Add mongodb root credentials to .env
        run: |
          ssh remote "
            cd $REPO_NAME
            echo 'MONGO_ROOT_USERNAME=$MONGO_ROOT_USERNAME' >> .env
            echo 'MONGO_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD' >> .env
          "
      - name: Pull latest image
        run: ssh remote "cd $REPO_NAME; docker compose -f database/docker-compose.yaml pull"
      - name: Stop existing containers
        run: ssh remote "cd $REPO_NAME; docker compose -f database/docker-compose.yaml down"
      - name: Prune dangling images
        run: ssh remote "docker image prune -f"
      - name: Clean local data files
        run: ssh remote "cd $REPO_NAME; sudo rm -rf data/mongo/db/*"
      - name: Start containers again
        run: ssh remote "cd $REPO_NAME; docker compose -f database/docker-compose.yaml --env-file .env up -d"
