name: Deploy to GCE

on:
  workflow_run:
    workflows: [Docker Image CI]
    types: [completed]
    branches: [main]

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  SSH_USER: ${{secrets.SSH_USER}}
  SSH_KEY: ${{secrets.SSH_KEY}}
  SSH_IP: ${{secrets.SSH_IP}}
  NGROK_AUTHTOKEN: ${{secrets.NGROK_AUTHTOKEN}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Get current repo name
        run: echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
      - name: Add IP to known_host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan $SSH_IP >> ~/.ssh/known_hosts
      - name: Add ssh private key
        run: |
          eval $(ssh-agent)
          ssh-add - <<< "$SSH_KEY"
          echo "$SSH_KEY" > ~/.ssh/id_gcp
          chmod 0600 ~/.ssh/id_gcp
      - name: Make a backup of master.pkl
        run: |
            ssh -i ~/.ssh/id_gcp $SSH_USER@$SSH_IP "
              cp $REPO_NAME/data/master.pkl $REPO_NAME/data/master.pkl.bkp
            "
      - name: Get the docker-compose file
        run: |
            ssh -i ~/.ssh/id_gcp $SSH_USER@$SSH_IP "
                if [ ! -d $REPO_NAME ]; then git clone https://github.com/blurrycontour/remember.git; fi
                cd remember
                git fetch
                git reset --hard $GITHUB_SHA
            "
      - name: Restore the backup of master.pkl
        run: |
          ssh -i ~/.ssh/id_gcp $SSH_USER@$SSH_IP "
            cp $REPO_NAME/data/master.pkl.bkp $REPO_NAME/data/master.pkl
          "
      - name: Add ngrok authtoken to .env
        run: ssh -i ~/.ssh/id_gcp $SSH_USER@$SSH_IP "cd $REPO_NAME; echo 'NGROK_AUTHTOKEN=$NGROK_AUTHTOKEN' >> .env"
      - name: Stop existing containers
        run: ssh -i ~/.ssh/id_gcp $SSH_USER@$SSH_IP "cd $REPO_NAME; docker compose down"
      - name: Pull latest image
        run: ssh -i ~/.ssh/id_gcp $SSH_USER@$SSH_IP "cd $REPO_NAME; docker compose pull"
      - name: Start containers again
        run: ssh -i ~/.ssh/id_gcp $SSH_USER@$SSH_IP "cd $REPO_NAME; docker compose up -d"
